feat: 新增Line Notify 機器人設定
SonicCloudOrg/sonic-client-web pull request #232
Opened 2022-12-30 11:58 UTC by ayumi760405

**在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：**

- [ ] 标题为fix、feat或doc开头
- [ ] 我已检查没有与此请求重复的拉取请求。
- [ ] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。

**填写PR内容：新增Line Notify 機器人設定**

2022-12-30 13:26 UTC, ZhouYixun commented on src/components/ProjectUpdate.vue
>  ];
`name`我建议为 LINE Notify

2022-12-30 13:26 UTC, ZhouYixun commented on src/views/Devices.vue
>  ];
同上

2022-12-30 13:26 UTC, ZhouYixun requested changes
感谢贡献，调整如上

2022-12-31 04:08 UTC, ayumi760405 commented on src/components/ProjectUpdate.vue
>  ];
好的沒問題

2022-12-31 06:59 UTC, ZhouYixun commented on src/components/ProjectUpdate.vue
>  ];
> 好的沒問題

Line还是使用全大写吧，跟Logo一致，小小调整一下

2022-12-31 06:59 UTC, ZhouYixun requested changes
Line还是使用全大写跟logo一致比较好，再稍微调整一下吧

2022-12-31 08:23 UTC, ayumi760405 commented
> Line还是使用全大写跟logo一致比较好，再稍微调整一下吧

已調整，謝謝。

2022-12-31 08:44 UTC, ZhouYixun approved these changes
感谢，允许合入

2022-12-31 08:44 UTC, merged