feat：应用程序面板，增加拉取“持续集成设置”->“安装包管理”中app的能力
SonicCloudOrg/sonic-client-web pull request #244
Opened 2023-05-07 08:06 UTC by caofengbin

> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [ ] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [ ] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [ ] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description

应用程序面板，新增加tab，通过选择持续集成安装包管理的方式进行安装。
前端改造：修改Android与ios端的“应用程序”面板，增加一个独立的vue组件，拉取指定项目下的安装包列表，用户选择特定的item之后，复用URL安装的方式，发送给agent端进行安装，

相关需求细节在社区中简单沟通：https://sonic-cloud.wiki/d/3064-app

2023-05-07 13:03 UTC, ZhouYixun commented on src/views/RemoteEmulator/IOSRemote.vue
> +              <el-tab-pane name="pushInstallPane">
这里复杂了，@tab-click 一般处理特殊交互的，一般点击不同tab之后就是默认绑定v-model自动变更的

strech不用加上=true，有这个属性就是true的意思了

2023-05-07 13:04 UTC, ZhouYixun commented on src/views/RemoteEmulator/IOSRemote.vue
> +}
这个方法可以去掉，看下方

2023-05-07 13:05 UTC, ZhouYixun commented on src/components/PackageList.vue
> +<script setup>
第一行下面插入一下LICENSE协议，可以参考其他文件copy一下

2023-05-07 13:06 UTC, ZhouYixun requested changes
有几个点稍微调整一下，改完记得安卓和iOS同步更改下哦，感谢贡献

2023-05-08 06:19 UTC, ZhouYixun approved these changes
看着没问题了，你都测试过了是吗

2023-05-08 06:21 UTC, ZhouYixun commented
我记得platform是这两个
```
        { text: 'Android', value: 'Android' },
        { text: 'iOS', value: 'iOS' },
```
你iOS那边怎么传的小写的

2023-05-08 06:22 UTC, ZhouYixun commented
固定的字符串不用做成
```
 :platform="'Android'"
```
直接
```
platform="Android"
```
这种就行

2023-05-08 06:52 UTC, caofengbin commented
> 看着没问题了，你都测试过了是吗



> 看着没问题了，你都测试过了是吗

嗯嗯，我这边都验证过了

2023-05-08 06:53 UTC, caofengbin commented
> 我记得platform是这两个
> 
> ```
>         { text: 'Android', value: 'Android' },
>         { text: 'iOS', value: 'iOS' },
> ```
> 
> 你iOS那边怎么传的小写的

我试了下数据库中匹配的时候，能忽略大小写匹配上，这种platform就是用来做搜索的，如果需要的话我改成之前项目中统一的规范形式

2023-05-08 06:55 UTC, caofengbin commented
> 固定的字符串不用做成
> 
> ```
>  :platform="'Android'"
> ```
> 
> 直接
> 
> ```
> platform="Android"
> ```
> 
> 这种就行

好的，这里我改下，对前端还不是很熟悉

2023-05-08 07:17 UTC, merged